version: '3.3'
services:
  mongo_db:
    image: "mongo:${MONGO_VERSION}"
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: "${USERNAME}/ui"
    ports:
      - "${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp"
    networks:
      - front_net
  post:
    image: "${USERNAME}/post"
    networks:
      - back_net
      - front_net
  comment:
    image: "${USERNAME}/comment"
    networks:
      - back_net
      - front_net

  prometheus:
    image: "${USERNAME}/prometheus"
    networks:
      - back_net
      - front_net
    ports:
      - "${PROM_HOST_PORT}:${PROM_CONTAINER_PORT}"

volumes:
  post_db:

networks:
  back_net:
     ipam:
         driver: default
         config:
            - subnet: 10.0.2.0/24
  front_net:
     ipam:
        driver: default
        config:
           - subnet: 10.0.1.0/24

