version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - ${PROM_HOST_PORT}:${PROM_CONTAINER_PORT}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: ${BACK_NET}
  front_net:
    ipam:
      driver: default
      config:
        - subnet: ${FRONT_NET}
