kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ZGKB3/hz7AJsB/QW1qbEwOIWfsZg4eWGRkQPafzYkI0=
      - identity: {}
