FROM alpine:3.6

ENV BUILD_PACKAGES bash ruby-dev build-base
ENV RUBY_PACKAGES ruby ruby-bundler

RUN apk update && \
    apk upgrade && \
    apk --no-cache add $BUILD_PACKAGES $RUBY_PACKAGES

RUN mkdir /usr/app
WORKDIR /usr/app

COPY . /usr/app

RUN bundle install


ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME
ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292
CMD ["puma"]

